<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\codewithmena.GymManagementSystem.BLL\codewithmena.GymManagementSystem.BLL.csproj" />
    <ProjectReference Include="..\codewithmena.GymManagementSystem.DAL\codewithmena.GymManagementSystem.DAL.csproj" />
  </ItemGroup>

</Project>

